### PR TITLE
feat: Mina zkApp 训练营 报名提交--fireWinters

### PR DESCRIPTION
**Pull request by fireWinters**

### CODE REVIEW

**Comment by smallfu6** [comment]
@fireWinters 把 Template.md 文件名改成你自己的名字

**Comment by qiusheng319** [comment]
hi, fireWinters, Please change the name of the Template. md file to your own name

**Comment by smallfu6** [comment]
@fireWinters 请补充钱包地址

**Comment by qiusheng319** [comment]
@fireWinters Please add wallet address

**Comment by fireWinters** [comment]
> @fireWinters hi, fireWinters, Please change the name of the Template. md file to your own name

Ok, it has been modified

**Comment by fireWinters** [comment]
> @fireWinters Please add wallet address

Ok, it has been modified

**Review by smallfu6 — APPROVED** [review]

**Review by qiusheng319 — APPROVED** [review]

**Pull request merged**
