### PR TITLE
Update Blossom.md

### PR DESCRIPTION
**Pull request by MackDing**
add knowledge and summary

### CODE REVIEW

**Comment by smallfu6** [comment]
@MackDing 不要在个人报名文件提交task，按照流程提交
image

**Review by MackDing — COMMENTED** [review]
@smallfu6 Updated directory structure, please review, thanks 
image

**Comment by smallfu6** [comment]
在报名文件中不要提交这些内容
image

**Review by MackDing — COMMENTED** [review]
removed redundancy , pls review , thanks @smallfu6

**Pull request merged**
